name: Bump
on:
  push:
    branches:
      - release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get tag
        id: tag
        run: |
          echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        id: bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: v${{ steps.tag.outputs.date }}-${{ steps.tag.outputs.sha_short }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.bump.outputs.new_tag }}
          tag_name: ${{ steps.bump.outputs.new_tag }}
          draft: true
